# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNWeChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNWeChat

  target 'RNWeChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNWeChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  
end
